// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt4;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241103183057_Seeddata")]
    partial class Seeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projekt4.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lunch"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dinner"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dessert"
                        });
                });

            modelBuilder.Entity("Projekt4.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Flour",
                            Quantity = "1 cup",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Milk",
                            Quantity = "1 cup",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Egg",
                            Quantity = "1",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sugar",
                            Quantity = "1 tbsp",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Butter",
                            Quantity = "1 tbsp",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bread",
                            Quantity = "2 slices",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cheese",
                            Quantity = "2 slices",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Butter",
                            Quantity = "1 tbsp",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Spaghetti",
                            Quantity = "200g",
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "Bacon",
                            Quantity = "100g",
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 11,
                            Name = "Parmesan Cheese",
                            Quantity = "50g",
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 12,
                            Name = "Egg",
                            Quantity = "1",
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 13,
                            Name = "Black Pepper",
                            Quantity = "to taste",
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 14,
                            Name = "Lettuce",
                            Quantity = "1 head",
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 15,
                            Name = "Chicken Breast",
                            Quantity = "200g",
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 16,
                            Name = "Croutons",
                            Quantity = "1/2 cup",
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 17,
                            Name = "Parmesan Cheese",
                            Quantity = "1/4 cup",
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 18,
                            Name = "Caesar Dressing",
                            Quantity = "3 tbsp",
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 19,
                            Name = "Eggs",
                            Quantity = "2",
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 20,
                            Name = "Salt",
                            Quantity = "Pinch",
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 21,
                            Name = "Pepper",
                            Quantity = "Pinch",
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 22,
                            Name = "Butter",
                            Quantity = "1 tbsp",
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 23,
                            Name = "Bread",
                            Quantity = "2 slices",
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 24,
                            Name = "Egg",
                            Quantity = "1",
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 25,
                            Name = "Milk",
                            Quantity = "1/4 cup",
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 26,
                            Name = "Sugar",
                            Quantity = "1 tbsp",
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 27,
                            Name = "Butter",
                            Quantity = "1 tbsp",
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 28,
                            Name = "Flour",
                            Quantity = "1 1/2 cups",
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 29,
                            Name = "Sugar",
                            Quantity = "1 cup",
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 30,
                            Name = "Cocoa Powder",
                            Quantity = "1/2 cup",
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 31,
                            Name = "Baking Powder",
                            Quantity = "1 tsp",
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 32,
                            Name = "Eggs",
                            Quantity = "2",
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 33,
                            Name = "Butter",
                            Quantity = "1/2 cup",
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 34,
                            Name = "Milk",
                            Quantity = "1 cup",
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 35,
                            Name = "Apples",
                            Quantity = "4, peeled and sliced",
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 36,
                            Name = "Sugar",
                            Quantity = "1/2 cup",
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 37,
                            Name = "Cinnamon",
                            Quantity = "1 tsp",
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 38,
                            Name = "Pie Crust",
                            Quantity = "1",
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 39,
                            Name = "Ground Beef",
                            Quantity = "200g",
                            RecipeId = 9
                        },
                        new
                        {
                            Id = 40,
                            Name = "Taco Seasoning",
                            Quantity = "1 packet",
                            RecipeId = 9
                        },
                        new
                        {
                            Id = 41,
                            Name = "Tortillas",
                            Quantity = "4",
                            RecipeId = 9
                        },
                        new
                        {
                            Id = 42,
                            Name = "Lettuce",
                            Quantity = "1/2 cup, shredded",
                            RecipeId = 9
                        },
                        new
                        {
                            Id = 43,
                            Name = "Cheese",
                            Quantity = "1/4 cup, shredded",
                            RecipeId = 9
                        },
                        new
                        {
                            Id = 44,
                            Name = "Chicken Breast",
                            Quantity = "200g",
                            RecipeId = 10
                        },
                        new
                        {
                            Id = 45,
                            Name = "Curry Powder",
                            Quantity = "1 tbsp",
                            RecipeId = 10
                        },
                        new
                        {
                            Id = 46,
                            Name = "Coconut Milk",
                            Quantity = "1 cup",
                            RecipeId = 10
                        },
                        new
                        {
                            Id = 47,
                            Name = "Onion",
                            Quantity = "1, chopped",
                            RecipeId = 10
                        },
                        new
                        {
                            Id = 48,
                            Name = "Garlic",
                            Quantity = "2 cloves, minced",
                            RecipeId = 10
                        },
                        new
                        {
                            Id = 49,
                            Name = "Beef",
                            Quantity = "500g, cubed",
                            RecipeId = 11
                        },
                        new
                        {
                            Id = 50,
                            Name = "Potatoes",
                            Quantity = "2, diced",
                            RecipeId = 11
                        },
                        new
                        {
                            Id = 51,
                            Name = "Carrots",
                            Quantity = "2, sliced",
                            RecipeId = 11
                        },
                        new
                        {
                            Id = 52,
                            Name = "Onion",
                            Quantity = "1, chopped",
                            RecipeId = 11
                        },
                        new
                        {
                            Id = 53,
                            Name = "Beef Broth",
                            Quantity = "2 cups",
                            RecipeId = 11
                        },
                        new
                        {
                            Id = 54,
                            Name = "Fish Fillets",
                            Quantity = "2",
                            RecipeId = 12
                        },
                        new
                        {
                            Id = 55,
                            Name = "Potatoes",
                            Quantity = "2, sliced",
                            RecipeId = 12
                        },
                        new
                        {
                            Id = 56,
                            Name = "Flour",
                            Quantity = "1/2 cup",
                            RecipeId = 12
                        },
                        new
                        {
                            Id = 57,
                            Name = "Salt",
                            Quantity = "to taste",
                            RecipeId = 12
                        },
                        new
                        {
                            Id = 58,
                            Name = "Vegetable Oil",
                            Quantity = "for frying",
                            RecipeId = 12
                        },
                        new
                        {
                            Id = 59,
                            Name = "Mushrooms",
                            Quantity = "200g, sliced",
                            RecipeId = 13
                        },
                        new
                        {
                            Id = 60,
                            Name = "Onion",
                            Quantity = "1, chopped",
                            RecipeId = 13
                        },
                        new
                        {
                            Id = 61,
                            Name = "Garlic",
                            Quantity = "1 clove, minced",
                            RecipeId = 13
                        },
                        new
                        {
                            Id = 62,
                            Name = "Cream",
                            Quantity = "1 cup",
                            RecipeId = 13
                        },
                        new
                        {
                            Id = 63,
                            Name = "Vegetable Broth",
                            Quantity = "1 cup",
                            RecipeId = 13
                        },
                        new
                        {
                            Id = 64,
                            Name = "Whole Chicken",
                            Quantity = "1",
                            RecipeId = 14
                        },
                        new
                        {
                            Id = 65,
                            Name = "Salt",
                            Quantity = "1 tbsp",
                            RecipeId = 14
                        },
                        new
                        {
                            Id = 66,
                            Name = "Black Pepper",
                            Quantity = "1 tsp",
                            RecipeId = 14
                        },
                        new
                        {
                            Id = 67,
                            Name = "Garlic",
                            Quantity = "3 cloves, minced",
                            RecipeId = 14
                        },
                        new
                        {
                            Id = 68,
                            Name = "Olive Oil",
                            Quantity = "2 tbsp",
                            RecipeId = 14
                        },
                        new
                        {
                            Id = 69,
                            Name = "Rosemary",
                            Quantity = "2 sprigs",
                            RecipeId = 14
                        },
                        new
                        {
                            Id = 70,
                            Name = "Flour",
                            Quantity = "2 cups",
                            RecipeId = 15
                        },
                        new
                        {
                            Id = 71,
                            Name = "Sugar",
                            Quantity = "1/4 cup",
                            RecipeId = 15
                        },
                        new
                        {
                            Id = 72,
                            Name = "Baking Powder",
                            Quantity = "2 tsp",
                            RecipeId = 15
                        },
                        new
                        {
                            Id = 73,
                            Name = "Eggs",
                            Quantity = "2",
                            RecipeId = 15
                        },
                        new
                        {
                            Id = 74,
                            Name = "Milk",
                            Quantity = "1 1/2 cups",
                            RecipeId = 15
                        },
                        new
                        {
                            Id = 75,
                            Name = "Butter",
                            Quantity = "1/2 cup, melted",
                            RecipeId = 15
                        },
                        new
                        {
                            Id = 76,
                            Name = "Pasta",
                            Quantity = "200g",
                            RecipeId = 16
                        },
                        new
                        {
                            Id = 77,
                            Name = "Cherry Tomatoes",
                            Quantity = "1 cup, halved",
                            RecipeId = 16
                        },
                        new
                        {
                            Id = 78,
                            Name = "Cucumber",
                            Quantity = "1, diced",
                            RecipeId = 16
                        },
                        new
                        {
                            Id = 79,
                            Name = "Olives",
                            Quantity = "1/4 cup, sliced",
                            RecipeId = 16
                        },
                        new
                        {
                            Id = 80,
                            Name = "Feta Cheese",
                            Quantity = "1/2 cup, crumbled",
                            RecipeId = 16
                        },
                        new
                        {
                            Id = 81,
                            Name = "Olive Oil",
                            Quantity = "2 tbsp",
                            RecipeId = 16
                        },
                        new
                        {
                            Id = 82,
                            Name = "Lemon Juice",
                            Quantity = "1 tbsp",
                            RecipeId = 16
                        },
                        new
                        {
                            Id = 83,
                            Name = "Pork Ribs",
                            Quantity = "1 rack",
                            RecipeId = 17
                        },
                        new
                        {
                            Id = 84,
                            Name = "BBQ Sauce",
                            Quantity = "1 cup",
                            RecipeId = 17
                        },
                        new
                        {
                            Id = 85,
                            Name = "Salt",
                            Quantity = "to taste",
                            RecipeId = 17
                        },
                        new
                        {
                            Id = 86,
                            Name = "Black Pepper",
                            Quantity = "to taste",
                            RecipeId = 17
                        },
                        new
                        {
                            Id = 87,
                            Name = "Garlic Powder",
                            Quantity = "1 tsp",
                            RecipeId = 17
                        },
                        new
                        {
                            Id = 88,
                            Name = "Beef Steak",
                            Quantity = "1",
                            RecipeId = 18
                        },
                        new
                        {
                            Id = 89,
                            Name = "Salt",
                            Quantity = "to taste",
                            RecipeId = 18
                        },
                        new
                        {
                            Id = 90,
                            Name = "Black Pepper",
                            Quantity = "to taste",
                            RecipeId = 18
                        },
                        new
                        {
                            Id = 91,
                            Name = "Olive Oil",
                            Quantity = "1 tbsp",
                            RecipeId = 18
                        },
                        new
                        {
                            Id = 92,
                            Name = "Butter",
                            Quantity = "1 tbsp",
                            RecipeId = 18
                        },
                        new
                        {
                            Id = 93,
                            Name = "Garlic",
                            Quantity = "1 clove, smashed",
                            RecipeId = 18
                        },
                        new
                        {
                            Id = 94,
                            Name = "Apple",
                            Quantity = "1, diced",
                            RecipeId = 19
                        },
                        new
                        {
                            Id = 95,
                            Name = "Banana",
                            Quantity = "1, sliced",
                            RecipeId = 19
                        },
                        new
                        {
                            Id = 96,
                            Name = "Grapes",
                            Quantity = "1/2 cup",
                            RecipeId = 19
                        },
                        new
                        {
                            Id = 97,
                            Name = "Orange",
                            Quantity = "1, segmented",
                            RecipeId = 19
                        },
                        new
                        {
                            Id = 98,
                            Name = "Strawberries",
                            Quantity = "1/2 cup, sliced",
                            RecipeId = 19
                        },
                        new
                        {
                            Id = 99,
                            Name = "Honey",
                            Quantity = "1 tbsp",
                            RecipeId = 19
                        },
                        new
                        {
                            Id = 100,
                            Name = "Mint Leaves",
                            Quantity = "for garnish",
                            RecipeId = 19
                        },
                        new
                        {
                            Id = 101,
                            Name = "Bananas",
                            Quantity = "3, mashed",
                            RecipeId = 20
                        },
                        new
                        {
                            Id = 102,
                            Name = "Flour",
                            Quantity = "1 1/2 cups",
                            RecipeId = 20
                        },
                        new
                        {
                            Id = 103,
                            Name = "Sugar",
                            Quantity = "1/2 cup",
                            RecipeId = 20
                        },
                        new
                        {
                            Id = 104,
                            Name = "Baking Soda",
                            Quantity = "1 tsp",
                            RecipeId = 20
                        },
                        new
                        {
                            Id = 105,
                            Name = "Salt",
                            Quantity = "1/4 tsp",
                            RecipeId = 20
                        },
                        new
                        {
                            Id = 106,
                            Name = "Egg",
                            Quantity = "1",
                            RecipeId = 20
                        },
                        new
                        {
                            Id = 107,
                            Name = "Butter",
                            Quantity = "1/3 cup, melted",
                            RecipeId = 20
                        });
                });

            modelBuilder.Entity("Projekt4.Models.Instruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("Step")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Instructions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Mix flour and milk.",
                            RecipeId = 1,
                            Step = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Add egg and whisk.",
                            RecipeId = 1,
                            Step = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Pour batter onto hot griddle and cook until golden brown.",
                            RecipeId = 1,
                            Step = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Butter one side of each bread slice.",
                            RecipeId = 2,
                            Step = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Place cheese between slices.",
                            RecipeId = 2,
                            Step = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Grill sandwich until golden brown on both sides.",
                            RecipeId = 2,
                            Step = 3
                        },
                        new
                        {
                            Id = 7,
                            Description = "Boil spaghetti in salted water until al dente.",
                            RecipeId = 3,
                            Step = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Cook bacon until crispy.",
                            RecipeId = 3,
                            Step = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "Mix cooked spaghetti with bacon, egg, and Parmesan cheese.",
                            RecipeId = 3,
                            Step = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "Chop lettuce and cook chicken breast.",
                            RecipeId = 4,
                            Step = 1
                        },
                        new
                        {
                            Id = 11,
                            Description = "Combine lettuce, chicken, croutons, and Parmesan cheese.",
                            RecipeId = 4,
                            Step = 2
                        },
                        new
                        {
                            Id = 12,
                            Description = "Drizzle Caesar dressing and toss well.",
                            RecipeId = 4,
                            Step = 3
                        },
                        new
                        {
                            Id = 13,
                            Description = "Crack eggs into a bowl, season with salt and pepper, and whisk.",
                            RecipeId = 5,
                            Step = 1
                        },
                        new
                        {
                            Id = 14,
                            Description = "Melt butter in a skillet over medium heat.",
                            RecipeId = 5,
                            Step = 2
                        },
                        new
                        {
                            Id = 15,
                            Description = "Pour eggs into the skillet and cook until set, folding gently.",
                            RecipeId = 5,
                            Step = 3
                        },
                        new
                        {
                            Id = 16,
                            Description = "Whisk egg, milk, and sugar in a bowl.",
                            RecipeId = 6,
                            Step = 1
                        },
                        new
                        {
                            Id = 17,
                            Description = "Dip each bread slice in the egg mixture.",
                            RecipeId = 6,
                            Step = 2
                        },
                        new
                        {
                            Id = 18,
                            Description = "Cook bread slices in a hot skillet until golden on both sides.",
                            RecipeId = 6,
                            Step = 3
                        },
                        new
                        {
                            Id = 19,
                            Description = "Preheat oven to 180°C (350°F). Grease and flour a cake pan.",
                            RecipeId = 7,
                            Step = 1
                        },
                        new
                        {
                            Id = 20,
                            Description = "Mix flour, sugar, cocoa powder, and baking powder.",
                            RecipeId = 7,
                            Step = 2
                        },
                        new
                        {
                            Id = 21,
                            Description = "Add eggs, butter, and milk, and mix until smooth.",
                            RecipeId = 7,
                            Step = 3
                        },
                        new
                        {
                            Id = 22,
                            Description = "Pour batter into pan and bake for 30–35 minutes.",
                            RecipeId = 7,
                            Step = 4
                        },
                        new
                        {
                            Id = 23,
                            Description = "Preheat oven to 200°C (400°F).",
                            RecipeId = 8,
                            Step = 1
                        },
                        new
                        {
                            Id = 24,
                            Description = "Combine apples, sugar, and cinnamon.",
                            RecipeId = 8,
                            Step = 2
                        },
                        new
                        {
                            Id = 25,
                            Description = "Pour apple mixture into pie crust and cover with top crust.",
                            RecipeId = 8,
                            Step = 3
                        },
                        new
                        {
                            Id = 26,
                            Description = "Bake for 45 minutes or until crust is golden.",
                            RecipeId = 8,
                            Step = 4
                        },
                        new
                        {
                            Id = 27,
                            Description = "Cook ground beef with taco seasoning until browned.",
                            RecipeId = 9,
                            Step = 1
                        },
                        new
                        {
                            Id = 28,
                            Description = "Warm tortillas in a skillet.",
                            RecipeId = 9,
                            Step = 2
                        },
                        new
                        {
                            Id = 29,
                            Description = "Assemble tacos with beef, lettuce, and cheese.",
                            RecipeId = 9,
                            Step = 3
                        },
                        new
                        {
                            Id = 30,
                            Description = "Sauté onion and garlic in a pot until softened.",
                            RecipeId = 10,
                            Step = 1
                        },
                        new
                        {
                            Id = 31,
                            Description = "Add chicken and curry powder; cook until browned.",
                            RecipeId = 10,
                            Step = 2
                        },
                        new
                        {
                            Id = 32,
                            Description = "Pour in coconut milk and simmer until chicken is cooked through.",
                            RecipeId = 10,
                            Step = 3
                        },
                        new
                        {
                            Id = 33,
                            Description = "Brown beef cubes in a pot.",
                            RecipeId = 11,
                            Step = 1
                        },
                        new
                        {
                            Id = 34,
                            Description = "Add potatoes, carrots, onion, and beef broth.",
                            RecipeId = 11,
                            Step = 2
                        },
                        new
                        {
                            Id = 35,
                            Description = "Simmer until vegetables and beef are tender.",
                            RecipeId = 11,
                            Step = 3
                        },
                        new
                        {
                            Id = 36,
                            Description = "Coat fish fillets in flour, salt, and pepper.",
                            RecipeId = 12,
                            Step = 1
                        },
                        new
                        {
                            Id = 37,
                            Description = "Fry fish and potato slices in hot oil until golden.",
                            RecipeId = 12,
                            Step = 2
                        },
                        new
                        {
                            Id = 38,
                            Description = "Sauté mushrooms, onion, and garlic until softened.",
                            RecipeId = 13,
                            Step = 1
                        },
                        new
                        {
                            Id = 39,
                            Description = "Add broth and cream; simmer until flavors blend.",
                            RecipeId = 13,
                            Step = 2
                        },
                        new
                        {
                            Id = 40,
                            Description = "Preheat oven to 180°C (350°F). Season chicken.",
                            RecipeId = 14,
                            Step = 1
                        },
                        new
                        {
                            Id = 41,
                            Description = "Roast chicken for 1 hour or until juices run clear.",
                            RecipeId = 14,
                            Step = 2
                        },
                        new
                        {
                            Id = 42,
                            Description = "Preheat waffle iron.",
                            RecipeId = 15,
                            Step = 1
                        },
                        new
                        {
                            Id = 43,
                            Description = "Mix flour, sugar, baking powder, eggs, milk, and butter.",
                            RecipeId = 15,
                            Step = 2
                        },
                        new
                        {
                            Id = 44,
                            Description = "Cook batter in waffle iron until golden.",
                            RecipeId = 15,
                            Step = 3
                        },
                        new
                        {
                            Id = 45,
                            Description = "Boil pasta until al dente; drain and cool.",
                            RecipeId = 16,
                            Step = 1
                        },
                        new
                        {
                            Id = 46,
                            Description = "Combine pasta, vegetables, cheese, olive oil, and lemon juice.",
                            RecipeId = 16,
                            Step = 2
                        },
                        new
                        {
                            Id = 47,
                            Description = "Season ribs and cook in a preheated oven at 150°C for 2 hours.",
                            RecipeId = 17,
                            Step = 1
                        },
                        new
                        {
                            Id = 48,
                            Description = "Brush ribs with BBQ sauce and cook until caramelized.",
                            RecipeId = 17,
                            Step = 2
                        },
                        new
                        {
                            Id = 49,
                            Description = "Season steak with salt and pepper.",
                            RecipeId = 18,
                            Step = 1
                        },
                        new
                        {
                            Id = 50,
                            Description = "Sear steak in hot skillet with butter and garlic until desired doneness.",
                            RecipeId = 18,
                            Step = 2
                        },
                        new
                        {
                            Id = 51,
                            Description = "Combine all fruits in a bowl.",
                            RecipeId = 19,
                            Step = 1
                        },
                        new
                        {
                            Id = 52,
                            Description = "Drizzle with honey and garnish with mint leaves.",
                            RecipeId = 19,
                            Step = 2
                        },
                        new
                        {
                            Id = 53,
                            Description = "Preheat oven to 175°C (350°F).",
                            RecipeId = 20,
                            Step = 1
                        },
                        new
                        {
                            Id = 54,
                            Description = "Mix mashed bananas, flour, sugar, baking soda, salt, egg, and butter.",
                            RecipeId = 20,
                            Step = 2
                        },
                        new
                        {
                            Id = 55,
                            Description = "Pour batter into loaf pan and bake for 60 minutes.",
                            RecipeId = 20,
                            Step = 3
                        });
                });

            modelBuilder.Entity("Projekt4.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "",
                            Name = "Pancakes"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "",
                            Name = "Grilled Cheese Sandwich"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "",
                            Name = "Spaghetti Carbonara"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "",
                            Name = "Caesar Salad"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "",
                            Name = "Omelette"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "",
                            Name = "French Toast"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "",
                            Name = "Chocolate Cake"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "",
                            Name = "Apple Pie"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "",
                            Name = "Tacos"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "",
                            Name = "Chicken Curry"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "",
                            Name = "Beef Stew"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "",
                            Name = "Fish and Chips"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "",
                            Name = "Mushroom Soup"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "",
                            Name = "Roast Chicken"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Description = "",
                            Name = "Waffles"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "",
                            Name = "Pasta Salad"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Description = "",
                            Name = "BBQ Ribs"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Description = "",
                            Name = "Steak"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "",
                            Name = "Fruit Salad"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "",
                            Name = "Banana Bread"
                        });
                });

            modelBuilder.Entity("Projekt4.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Projekt4.Models.Ingredient", b =>
                {
                    b.HasOne("Projekt4.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Projekt4.Models.Instruction", b =>
                {
                    b.HasOne("Projekt4.Models.Recipe", "Recipe")
                        .WithMany("Instructions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Projekt4.Models.Recipe", b =>
                {
                    b.HasOne("Projekt4.Models.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Projekt4.Models.Category", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Projekt4.Models.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Instructions");
                });
#pragma warning restore 612, 618
        }
    }
}
